<script setup lang="ts">
import { GitPullRequestArrow, SquareArrowOutUpRight } from "@lucide/vue";
import { computed, ref } from "vue";
import { toast } from "vue-sonner";
import { Button } from "@/components/ui/button";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Spinner } from "@/components/ui/spinner";
import {
  TagsInput,
  TagsInputInput,
  TagsInputItem,
  TagsInputItemDelete,
  TagsInputItemText,
} from "@/components/ui/tags-input";
import ErrorNotice from "@/shared/components/ErrorNotice.vue";
import type { GithubSetup, SetupPullRequestInput } from "@/shared/types/ci";
import type { useGithubSetup } from "../../composables/useGithubSetup";
import { workflowState } from "../../lib/github-setup";

const props = defineProps<{
  setup: GithubSetup;
  pullRequest: ReturnType<typeof useGithubSetup>["pullRequest"];
}>();

const CLIENT = /^[a-z0-9][a-z0-9-]{0,56}$/;

const state = computed(() => workflowState(props.setup));
const showForm = ref(false);
const devBranch = ref("dev");
const stagingBranch = ref("staging");
const appDir = ref("");
const clients = ref<string[]>([]);
const problem = ref<string | null>(null);

const offerForm = computed(() => state.value.kind === "missing" || showForm.value);

function normaliseClients(values: unknown[]) {
  clients.value = [
    ...new Set(
      values
        .map((value) =>
          String(value)
            .trim()
            .toLowerCase()
            .replace(/^prod-/, ""),
        )
        .filter(Boolean),
    ),
  ];
}

function submit() {
  problem.value = null;
  const branches = [props.setup.default_branch, devBranch.value.trim(), stagingBranch.value.trim()];
  if (new Set(branches).size !== 3) {
    problem.value = "The default, dev and staging branches must be three different branches.";
    return;
  }
  const bad = clients.value.find((client) => !CLIENT.test(client));
  if (bad) {
    problem.value = `"${bad}" is not a usable client name: lowercase letters, digits and dashes.`;
    return;
  }
  const input: SetupPullRequestInput = {
    dev_branch: devBranch.value.trim() || undefined,
    staging_branch: stagingBranch.value.trim() || undefined,
    clients: clients.value,
    app_dir: appDir.value.trim() || undefined,
  };
  props.pullRequest.mutate(input, {
    onSuccess: ({ pull_request: pr, created }) => {
      showForm.value = false;
      toast.success(
        created
          ? `Pull request #${pr.number} opened`
          : `Pull request #${pr.number} is already open`,
        {
          action: pr.html_url
            ? {
                label: "Review",
                onClick: () => window.open(pr.html_url, "_blank", "noopener,noreferrer"),
              }
            : undefined,
        },
      );
    },
  });
}
</script>

<template>
  <div class="space-y-3 text-sm">
    <p class="text-muted-foreground text-pretty">
      Capuchoo's workflow lives at
      <code class="text-foreground font-mono text-xs">{{ props.setup.workflow.path }}</code
      >. It publishes on push to your release branches and runs what you start from here.
    </p>

    <div v-if="state.kind === 'pull-request'" class="flex flex-wrap items-center gap-2">
      <Button as-child size="sm">
        <a :href="state.url" target="_blank" rel="noopener noreferrer">
          <GitPullRequestArrow />
          Review and merge #{{ state.number }}
          <SquareArrowOutUpRight class="size-3.5" />
        </a>
      </Button>
      <span class="text-muted-foreground text-xs">The checklist updates once it is merged.</span>
    </div>

    <div v-else-if="state.kind === 'foreign'" class="space-y-2">
      <p>
        A workflow already exists there and was not generated by Capuchoo, so runs may not report
        back.
        <a
          v-if="state.url"
          :href="state.url"
          target="_blank"
          rel="noopener noreferrer"
          class="text-primary hover:underline"
          >View the file</a
        >
      </p>
      <Button v-if="!showForm" size="sm" variant="outline" @click="showForm = true">
        Propose Capuchoo's workflow instead
      </Button>
    </div>

    <div v-else-if="state.kind === 'outdated'" class="space-y-2">
      <p>
        Generated by Capuchoo {{ state.version ?? "an older version" }}; this server writes
        {{ state.expected }}.
      </p>
      <Button v-if="!showForm" size="sm" variant="outline" @click="showForm = true">
        Open an update pull request
      </Button>
    </div>

    <p v-else-if="state.kind === 'ready'" class="flex flex-wrap items-center gap-2">
      <span
        >In place on <span class="font-mono text-xs">{{ props.setup.default_branch }}</span>
        <template v-if="state.version"> · Capuchoo {{ state.version }}</template></span
      >
      <a
        v-if="state.url"
        :href="state.url"
        target="_blank"
        rel="noopener noreferrer"
        class="text-primary inline-flex items-center gap-1 hover:underline"
        >View <SquareArrowOutUpRight class="size-3"
      /></a>
    </p>

    <form
      v-if="offerForm"
      class="bg-surface space-y-4 rounded-md border p-4"
      @submit.prevent="submit"
    >
      <FieldGroup class="gap-4">
        <div class="grid gap-4 sm:grid-cols-3">
          <Field>
            <FieldLabel for="wf-dev">Dev branch</FieldLabel>
            <Input id="wf-dev" v-model="devBranch" class="font-mono" spellcheck="false" />
          </Field>
          <Field>
            <FieldLabel for="wf-staging">Staging branch</FieldLabel>
            <Input id="wf-staging" v-model="stagingBranch" class="font-mono" spellcheck="false" />
          </Field>
          <Field>
            <FieldLabel for="wf-dir">App directory</FieldLabel>
            <Input
              id="wf-dir"
              v-model="appDir"
              class="font-mono"
              placeholder="."
              spellcheck="false"
            />
          </Field>
        </div>
        <FieldDescription class="-mt-2">
          A push to {{ props.setup.default_branch }} rehearses, a tag publishes prod, the dev and
          staging branches publish to their channels.
          <template v-if="props.setup.package_manager">
            Dependencies install with {{ props.setup.package_manager }}.</template
          >
        </FieldDescription>
        <Field>
          <FieldLabel for="wf-clients">Clients</FieldLabel>
          <TagsInput
            :model-value="clients"
            add-on-blur
            add-on-paste
            :delimiter="/[\s,]+/"
            @update:model-value="normaliseClients"
          >
            <TagsInputItem v-for="client in clients" :key="client" :value="client">
              <TagsInputItemText class="font-mono" />
              <TagsInputItemDelete />
            </TagsInputItem>
            <TagsInputInput id="wf-clients" placeholder="acme, globex…" class="font-mono" />
          </TagsInput>
          <FieldDescription>
            Each one gets a deliver target, pointing
            <span class="font-mono">prod-&lt;client&gt;</span>.
          </FieldDescription>
        </Field>
      </FieldGroup>
      <p v-if="problem" class="text-destructive text-sm">{{ problem }}</p>
      <ErrorNotice v-if="props.pullRequest.error.value" :error="props.pullRequest.error.value" />
      <div class="flex justify-end gap-2">
        <Button v-if="showForm" type="button" variant="ghost" size="sm" @click="showForm = false"
          >Cancel</Button
        >
        <Button type="submit" size="sm" :disabled="props.pullRequest.isPending.value">
          <Spinner v-if="props.pullRequest.isPending.value" />
          <GitPullRequestArrow v-else />
          Open setup pull request
        </Button>
      </div>
    </form>
  </div>
</template>
