import {
  Container,
  Database,
  GitBranch,
  HardDrive,
  Server,
  Smartphone,
  SquareTerminal,
  type LucideIcon,
} from "@lucide/vue";

export interface Step {
  title: string;
  description: string;
  code?: string;
}

export const STEPS: readonly Step[] = [
  {
    title: "Add the updater",
    description:
      "The Vue runtime and the Capacitor plugins it builds on. It checks for updates, downloads in the background, verifies the signature and applies on the next launch or when the user taps Restart.",
    code: "pnpm add @capuchoo/updater @capgo/capacitor-updater",
  },
  {
    title: "Deploy from your machine or CI",
    description:
      "The CLI builds with the flavour the channel asks for, signs the result and uploads it once.",
    code: "capuchoo deploy ota --channel prod",
  },
  {
    title: "Point a channel",
    description:
      "Devices on that channel pick the release up on their next check. Move it back just as explicitly.",
    code: "capuchoo channel point prod --version 1.4.3",
  },
];

export interface Timeline {
  label: string;
  steps: readonly string[];
  outcome: string;
  tone: "slow" | "fast";
}

/** The two paths a fix can take once the code is written. */
export const TIMELINES: readonly Timeline[] = [
  {
    label: "Through the store",
    steps: ["Build the binary", "Submit", "Wait for review", "Staged rollout", "Users update"],
    outcome: "Days, and users choose when",
    tone: "slow",
  },
  {
    label: "Over the air",
    steps: ["capuchoo deploy", "channel point", "Next update check"],
    outcome: "Minutes, on the channels you pick",
    tone: "fast",
  },
];

export interface Integration {
  name: string;
  detail: string;
  icon: LucideIcon;
}

/** Only what the code talks to today. */
export const INTEGRATIONS: readonly Integration[] = [
  { name: "Capacitor 7 and 8", detail: "Vue 3 apps, Android today", icon: Smartphone },
  { name: "Capgo updater", detail: "@capgo/capacitor-updater", icon: HardDrive },
  { name: "GitLab CI", detail: "pipeline template, build webhooks", icon: GitBranch },
  { name: "Any CI", detail: "--json output, env credentials", icon: SquareTerminal },
  { name: "PostgreSQL", detail: "the only database", icon: Database },
  { name: "S3-compatible", detail: "R2, MinIO, AWS S3", icon: HardDrive },
  { name: "Docker + Traefik", detail: "compose file included", icon: Container },
  { name: "Render", detail: "Blueprint included", icon: Server },
];

export interface HostingOption {
  title: string;
  description: string;
  points: readonly string[];
  link: "selfHosting" | "repository";
}

export const HOSTING: readonly HostingOption[] = [
  {
    title: "Your own server",
    description: "Docker Compose with Traefik on any VPS. The path we recommend for production.",
    points: [
      "Server, dashboard and PostgreSQL in one file",
      "Daily pg_dump backups kept 14 days",
      "Artefacts on a volume or S3-compatible storage",
    ],
    link: "selfHosting",
  },
  {
    title: "Render",
    description: "A Blueprint creates the server, the dashboard and the database for a trial.",
    points: [
      "Secrets generated by Render, never typed by hand",
      "Dashboard proxies /api, so sessions stay first-party",
      "Free plans sleep and expire: fine for testing only",
    ],
    link: "selfHosting",
  },
  {
    title: "Your data, your rules",
    description: "No Capuchoo cloud. Devices talk to the server you run, under your domain.",
    points: [
      "Pick a hostname you will keep: it is compiled into every APK",
      "Device events purged after 90 days by default",
      "Location is off unless the app turns it on",
    ],
    link: "repository",
  },
];

export interface Question {
  question: string;
  answer: string;
}

export const FAQ: readonly Question[] = [
  {
    question: "What can an over-the-air update change?",
    answer:
      "The web layer: your HTML, CSS, JavaScript and assets. Native code, plugins and permissions change with a new APK, which Capuchoo also delivers and installs through Android's installer.",
  },
  {
    question: "What happens if an update breaks the app?",
    answer:
      "The app confirms each new bundle once it has booted. If it does not in time, the plugin returns to the previous bundle, and the failure shows up on the channel. You can then roll the channel back.",
  },
  {
    question: "How do client channels work with one APK?",
    answer:
      "The server decides each device's channel: a dashboard assignment first, then the channel the device chose (when allowed), then the one its build reports. The binary is the same for every customer.",
  },
  {
    question: "Can a native-only Android app use it?",
    answer:
      "Not today. The CLI builds through a Capacitor project and the updater runs in its WebView. The server speaks plain HTTP, so a Kotlin client and publishing an APK built by any Gradle project are what native-only support would need.",
  },
  {
    question: "Does it support iOS?",
    answer:
      "The delivery model and the updater are platform-neutral, but Android is what runs in production today. Native iOS builds are not produced by the CLI.",
  },
];
