import {
  GITHUB_WORKFLOW_SECRETS,
  GITHUB_WORKFLOW_VARIABLE,
  renderGithubWorkflow,
  type GithubWorkflowSecret,
} from "@capuchoo/core";
import type { Deps } from "../http/context";
import { badRequest } from "../lib/errors";
import { asInstallation, type GithubSession } from "./client";
import { GithubApiError } from "./http";
import type { GithubLink } from "./repository-link";
import { asRecord, asText } from "./run-mapper";

export const SETUP_BRANCH = "capuchoo/setup";
const GENERATED = /^# Generated by Capuchoo (\S+)/;
const MAX_SECRET_CHARS = 96 * 1024;
const RAW = "application/vnd.github.raw+json";

const SECRET_REQUIREMENT: Record<GithubWorkflowSecret, "always" | "native" | "optional"> = {
  CAPUCHOO_API_KEY: "always",
  CAPUCHOO_SIGNING_KEY: "optional",
  ANDROID_KEYSTORE_BASE64: "native",
  ANDROID_KEYSTORE_PASSWORD: "native",
  ANDROID_KEY_ALIAS: "native",
  ANDROID_KEY_PASSWORD: "native",
};

const LOCKFILES: Array<[string, "pnpm" | "npm" | "yarn" | "bun"]> = [
  ["pnpm-lock.yaml", "pnpm"],
  ["bun.lock", "bun"],
  ["bun.lockb", "bun"],
  ["yarn.lock", "yarn"],
  ["package-lock.json", "npm"],
];

const contentPath = (path: string) => path.split("/").map(encodeURIComponent).join("/");

async function readFile(github: GithubSession, link: GithubLink, path: string, ref: string) {
  return github.call<string>("GET", `/repos/${link.repository}/contents/${contentPath(path)}`, {
    query: { ref },
    accept: RAW,
    allow: [404],
  });
}

async function setupPullRequest(github: GithubSession, link: GithubLink, state: "open" | "all") {
  const owner = link.repository.split("/")[0];
  const pulls = await github.call<unknown[]>("GET", `/repos/${link.repository}/pulls`, {
    query: {
      head: `${owner}:${SETUP_BRANCH}`,
      state,
      per_page: 1,
      sort: "created",
      direction: "desc",
    },
  });
  const pull = asRecord(Array.isArray(pulls) ? pulls[0] : null);
  if (typeof pull.number !== "number") return null;
  return {
    number: pull.number,
    html_url: asText(pull.html_url, 2000) ?? "",
    state: pull.merged_at
      ? ("merged" as const)
      : pull.state === "open"
        ? ("open" as const)
        : ("closed" as const),
  };
}

/** Everything the dashboard's setup checklist shows, read live from the repository. */
export async function githubSetupStatus(deps: Deps, link: GithubLink, endpoint: string) {
  const github = asInstallation(deps, link.installationId);
  const repo = asRecord(await github.call<unknown>("GET", `/repos/${link.repository}`));
  const defaultBranch = asText(repo.default_branch) ?? link.defaultBranch;
  const [workflow, pull, secrets, variable, root, expectedVersion] = await Promise.all([
    readFile(github, link, link.workflowPath, defaultBranch),
    setupPullRequest(github, link, "all"),
    github.list<{ name?: string }>(`/repos/${link.repository}/actions/secrets`, {
      key: "secrets",
      limit: 300,
    }),
    github.call<{ value?: string }>(
      `GET`,
      `/repos/${link.repository}/actions/variables/${GITHUB_WORKFLOW_VARIABLE}`,
      {
        allow: [404],
      },
    ),
    github.call<unknown[]>("GET", `/repos/${link.repository}/contents`, {
      query: { ref: defaultBranch },
      allow: [404],
    }),
    latestCliVersion(deps),
  ]);
  const present = new Set(secrets.items.map((secret) => secret.name));
  const rootNames = new Set(
    (Array.isArray(root) ? root : []).map((entry) => asText(asRecord(entry).name)),
  );
  const text = typeof workflow === "string" ? workflow : null;
  const version = text ? (GENERATED.exec(text)?.[1] ?? null) : null;
  return {
    default_branch: defaultBranch,
    workflow: {
      path: link.workflowPath,
      exists: text !== null,
      generated: version !== null,
      version,
      expected_version: expectedVersion,
      html_url: text ? `${link.htmlUrl}/blob/${defaultBranch}/${link.workflowPath}` : null,
    },
    pull_request: pull,
    secrets: GITHUB_WORKFLOW_SECRETS.map((name) => ({
      name,
      present: present.has(name),
      required: SECRET_REQUIREMENT[name],
    })),
    variable: {
      name: GITHUB_WORKFLOW_VARIABLE,
      value: variable?.value ?? null,
      expected: endpoint,
    },
    package_manager: LOCKFILES.find(([file]) => rootNames.has(file))?.[1] ?? null,
  };
}

const CLI_VERSION_TTL_MS = 60 * 60_000;

/** The newest published CLI, cached for an hour; null when the registry cannot be reached. */
async function latestCliVersion(deps: Deps): Promise<string | null> {
  const now = deps.now().getTime();
  const cached = deps.ci.cliVersion;
  if (cached && cached.expiresAt > now) return cached.value;
  let value: string | null = null;
  try {
    const response = await deps.ci.fetch("https://registry.npmjs.org/@capuchoo/cli/latest", {
      headers: { accept: "application/json" },
      signal: AbortSignal.timeout(5_000),
    });
    const payload = (await response.json()) as { version?: unknown };
    value =
      typeof payload.version === "string" && /^\d+\.\d+\.\d+/.test(payload.version)
        ? payload.version
        : null;
  } catch {
    value = null;
  }
  deps.ci.cliVersion = { value, expiresAt: now + (value ? CLI_VERSION_TTL_MS : 60_000) };
  return value;
}

export interface SetupPullRequestInput {
  dev_branch?: unknown;
  staging_branch?: unknown;
  clients?: unknown;
  app_dir?: unknown;
  cli_version?: unknown;
}

const optional = (value: unknown): string | undefined =>
  typeof value === "string" && value.trim() ? value.trim() : undefined;

/**
 * Proposes the workflow as a pull request from `capuchoo/setup`, never a direct commit: a person
 * reviews what will run with the repository's secrets. While a setup pull request is open its
 * branch is updated in place, so commits someone added survive; a leftover branch with no open
 * pull request is reset to the default branch first.
 */
export async function openSetupPullRequest(
  deps: Deps,
  link: GithubLink,
  input: SetupPullRequestInput,
) {
  const github = asInstallation(deps, link.installationId);
  const repo = asRecord(await github.call<unknown>("GET", `/repos/${link.repository}`));
  const base = asText(repo.default_branch) ?? link.defaultBranch;
  const clients = Array.isArray(input.clients)
    ? input.clients.filter((client): client is string => typeof client === "string")
    : typeof input.clients === "string"
      ? input.clients.split(",")
      : [];

  let content: string;
  try {
    content = renderGithubWorkflow({
      cliVersion: optional(input.cli_version) ?? (await latestCliVersion(deps)) ?? "latest",
      appDir: optional(input.app_dir),
      defaultBranch: base,
      devBranch: optional(input.dev_branch),
      stagingBranch: optional(input.staging_branch),
      clients,
    });
  } catch (error) {
    throw badRequest(
      error instanceof Error ? error.message : "The workflow options are invalid",
      "workflow_options",
    );
  }

  const open = await setupPullRequest(github, link, "open");
  const branchRef = await github.call<unknown>(
    "GET",
    `/repos/${link.repository}/git/ref/heads/${SETUP_BRANCH}`,
    {
      allow: [404],
    },
  );
  if (!open || !branchRef) {
    const head = asRecord(
      asRecord(
        await github.call<unknown>(
          "GET",
          `/repos/${link.repository}/git/ref/heads/${encodeURIComponent(base)}`,
        ),
      ).object,
    );
    const sha = asText(head.sha, 64);
    if (!sha) throw badRequest(`The default branch ${base} has no commits`, "github_empty");
    if (branchRef) {
      await github.call("PATCH", `/repos/${link.repository}/git/refs/heads/${SETUP_BRANCH}`, {
        body: { sha, force: true },
      });
    } else {
      await github.call("POST", `/repos/${link.repository}/git/refs`, {
        body: { ref: `refs/heads/${SETUP_BRANCH}`, sha },
      });
    }
  }

  const existing = asRecord(
    await github.call<unknown>(
      "GET",
      `/repos/${link.repository}/contents/${contentPath(link.workflowPath)}`,
      {
        query: { ref: SETUP_BRANCH },
        allow: [404],
      },
    ),
  );
  const current =
    typeof existing.content === "string"
      ? Buffer.from(existing.content, "base64").toString("utf8")
      : null;
  if (current !== content) {
    await github.call(
      "PUT",
      `/repos/${link.repository}/contents/${contentPath(link.workflowPath)}`,
      {
        body: {
          message:
            current === null ? "ci: add the Capuchoo workflow" : "ci: update the Capuchoo workflow",
          content: Buffer.from(content, "utf8").toString("base64"),
          branch: SETUP_BRANCH,
          ...(typeof existing.sha === "string" ? { sha: existing.sha } : {}),
        },
      },
    );
  }

  if (open) return { pull_request: open, created: false };
  const created = asRecord(
    await github.call<unknown>("POST", `/repos/${link.repository}/pulls`, {
      body: {
        title: "Add the Capuchoo release workflow",
        head: SETUP_BRANCH,
        base,
        body: [
          "Adds `" + link.workflowPath + "`, generated by Capuchoo.",
          "",
          "- Pushes to the dev and staging branches publish an OTA update to that channel; a `v*` tag publishes prod.",
          "- Pull requests and pushes to the default branch rehearse the deploy without uploading.",
          "- Native builds and client deliveries run when started from GitHub or the Capuchoo dashboard.",
          "",
          "Before merging, set the `CAPUCHOO_ENDPOINT` variable and the `CAPUCHOO_API_KEY` secret (the dashboard's CI settings do both).",
        ].join("\n"),
        maintainer_can_modify: true,
      },
    }),
  );
  return {
    pull_request: {
      number: Number(created.number),
      html_url: asText(created.html_url, 2000) ?? "",
      state: "open" as const,
    },
    created: true,
  };
}

export async function repositoryPublicKey(deps: Deps, link: GithubLink) {
  const key = asRecord(
    await asInstallation(deps, link.installationId).call<unknown>(
      "GET",
      `/repos/${link.repository}/actions/secrets/public-key`,
    ),
  );
  const keyId = asText(key.key_id);
  const value = asText(key.key, 200);
  if (!keyId || !value) throw new GithubApiError(502, "no public key for this repository");
  return { key_id: keyId, key: value };
}

/** Relays secrets the browser already encrypted for this repository; nothing here can read them. */
export async function storeSecrets(
  deps: Deps,
  link: GithubLink,
  body: Record<string, unknown>,
): Promise<string[]> {
  const entries = Array.isArray(body.secrets) ? body.secrets.map(asRecord) : [];
  if (entries.length === 0 || entries.length > GITHUB_WORKFLOW_SECRETS.length)
    throw badRequest("secrets must list 1 to 6 entries");
  const allowed = new Set<string>(GITHUB_WORKFLOW_SECRETS);
  const prepared = entries.map((entry) => {
    const name = asText(entry.name);
    const value = typeof entry.encrypted_value === "string" ? entry.encrypted_value : "";
    const keyId = asText(entry.key_id);
    if (!name || !allowed.has(name))
      throw badRequest(`${name ?? "A secret"} is not a secret Capuchoo manages`);
    if (!value || value.length > MAX_SECRET_CHARS || !/^[A-Za-z0-9+/=]+$/.test(value))
      throw badRequest(`${name} is not an encrypted value`);
    if (!keyId) throw badRequest(`${name} needs the key_id it was encrypted for`);
    return { name, value, keyId };
  });
  const github = asInstallation(deps, link.installationId);
  for (const secret of prepared) {
    await github.call("PUT", `/repos/${link.repository}/actions/secrets/${secret.name}`, {
      body: { encrypted_value: secret.value, key_id: secret.keyId },
    });
  }
  return prepared.map((secret) => secret.name);
}

export async function storeEndpointVariable(
  deps: Deps,
  link: GithubLink,
  value: string,
): Promise<void> {
  const github = asInstallation(deps, link.installationId);
  const path = `/repos/${link.repository}/actions/variables`;
  const existing = await github.call<unknown>("GET", `${path}/${GITHUB_WORKFLOW_VARIABLE}`, {
    allow: [404],
  });
  if (existing) {
    await github.call("PATCH", `${path}/${GITHUB_WORKFLOW_VARIABLE}`, {
      body: { name: GITHUB_WORKFLOW_VARIABLE, value },
    });
  } else {
    await github.call("POST", path, { body: { name: GITHUB_WORKFLOW_VARIABLE, value } });
  }
}
