/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/shared/components/error/404.vue')['default']
    ActivityListItem: typeof import('./src/shared/components/app/ActivityListItem.vue')['default']
    ActivityView: typeof import('./src/modules/activity/views/ActivityView.vue')['default']
    AppDetailView: typeof import('./src/modules/apps/views/AppDetailView.vue')['default']
    AppearanceView: typeof import('./src/modules/profile/views/AppearanceView.vue')['default']
    AppIcon: typeof import('./src/shared/components/app/AppIcon.vue')['default']
    AppListItem: typeof import('./src/modules/apps/components/AppListItem.vue')['default']
    AppsView: typeof import('./src/modules/apps/views/AppsView.vue')['default']
    BuildListItem: typeof import('./src/modules/apps/components/BuildListItem.vue')['default']
    BuildView: typeof import('./src/modules/apps/views/BuildView.vue')['default']
    CapTabbar: typeof import('./src/shared/components/navigation/CapTabbar.vue')['default']
    ChannelListItem: typeof import('./src/modules/apps/components/ChannelListItem.vue')['default']
    ColorThemesView: typeof import('./src/modules/profile/views/ColorThemesView.vue')['default']
    DeliverSheet: typeof import('./src/modules/apps/components/DeliverSheet.vue')['default']
    EmptyState: typeof import('./src/shared/components/app/EmptyState.vue')['default']
    EnvironmentChip: typeof import('./src/shared/components/app/EnvironmentChip.vue')['default']
    F7App: typeof import('framework7-vue')['f7App']
    F7Badge: typeof import('framework7-vue')['f7Badge']
    F7Block: typeof import('framework7-vue')['f7Block']
    F7BlockFooter: typeof import('framework7-vue')['f7BlockFooter']
    F7BlockTitle: typeof import('framework7-vue')['f7BlockTitle']
    F7Button: typeof import('framework7-vue')['f7Button']
    F7Chip: typeof import('framework7-vue')['f7Chip']
    F7Icon: typeof import('framework7-vue')['f7Icon']
    F7Link: typeof import('framework7-vue')['f7Link']
    F7List: typeof import('framework7-vue')['f7List']
    F7ListButton: typeof import('framework7-vue')['f7ListButton']
    F7ListInput: typeof import('framework7-vue')['f7ListInput']
    F7ListItem: typeof import('framework7-vue')['f7ListItem']
    F7Navbar: typeof import('framework7-vue')['f7Navbar']
    F7NavRight: typeof import('framework7-vue')['f7NavRight']
    F7Page: typeof import('framework7-vue')['f7Page']
    F7PageContent: typeof import('framework7-vue')['f7PageContent']
    F7Searchbar: typeof import('framework7-vue')['f7Searchbar']
    F7Sheet: typeof import('framework7-vue')['f7Sheet']
    F7Toggle: typeof import('framework7-vue')['f7Toggle']
    F7Toolbar: typeof import('framework7-vue')['f7Toolbar']
    F7View: typeof import('framework7-vue')['f7View']
    F7Views: typeof import('framework7-vue')['f7Views']
    InstallControl: typeof import('./src/modules/apps/components/InstallControl.vue')['default']
    LaneDots: typeof import('./src/modules/apps/components/LaneDots.vue')['default']
    LiveIndicator: typeof import('./src/shared/components/app/LiveIndicator.vue')['default']
    LoadingIndicator: typeof import('./src/shared/components/progress/LoadingIndicator.vue')['default']
    MaterialShape: typeof import('./src/shared/components/shape/MaterialShape.vue')['default']
    NotificationSettingsView: typeof import('./src/modules/profile/views/NotificationSettingsView.vue')['default']
    PhoneCard: typeof import('./src/modules/apps/components/PhoneCard.vue')['default']
    PhoneLine: typeof import('./src/modules/apps/components/PhoneLine.vue')['default']
    ProfileView: typeof import('./src/modules/profile/views/ProfileView.vue')['default']
    PullToRefresh: typeof import('./src/shared/components/refresh/PullToRefresh.vue')['default']
    SceneInstall: typeof import('./src/modules/welcome/components/scenes/SceneInstall.vue')['default']
    SceneLanes: typeof import('./src/modules/welcome/components/scenes/SceneLanes.vue')['default']
    SceneNotify: typeof import('./src/modules/welcome/components/scenes/SceneNotify.vue')['default']
    SceneRoles: typeof import('./src/modules/welcome/components/scenes/SceneRoles.vue')['default']
    SeedSwatch: typeof import('./src/modules/profile/components/SeedSwatch.vue')['default']
    SignInView: typeof import('./src/modules/auth/views/SignInView.vue')['default']
    ThemePreview: typeof import('./src/modules/profile/components/ThemePreview.vue')['default']
    UpdateListItem: typeof import('./src/modules/apps/components/UpdateListItem.vue')['default']
    VariantTile: typeof import('./src/modules/profile/components/VariantTile.vue')['default']
    WavyProgress: typeof import('./src/shared/components/progress/WavyProgress.vue')['default']
    WelcomeView: typeof import('./src/modules/welcome/views/WelcomeView.vue')['default']
  }
}
