/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/shared/components/error/404.vue')['default']
    ActivityLine: typeof import('./src/shared/components/app/ActivityLine.vue')['default']
    ActivityView: typeof import('./src/modules/activity/views/ActivityView.vue')['default']
    AppCard: typeof import('./src/modules/apps/components/AppCard.vue')['default']
    AppDetailView: typeof import('./src/modules/apps/views/AppDetailView.vue')['default']
    AppIcon: typeof import('./src/shared/components/app/AppIcon.vue')['default']
    AppsView: typeof import('./src/modules/apps/views/AppsView.vue')['default']
    BuildItem: typeof import('./src/modules/apps/components/BuildItem.vue')['default']
    BuildView: typeof import('./src/modules/apps/views/BuildView.vue')['default']
    ChannelCard: typeof import('./src/modules/apps/components/ChannelCard.vue')['default']
    DeliverSheet: typeof import('./src/modules/apps/components/DeliverSheet.vue')['default']
    EmptyState: typeof import('./src/shared/components/app/EmptyState.vue')['default']
    EnvironmentChip: typeof import('./src/shared/components/app/EnvironmentChip.vue')['default']
    F7App: typeof import('framework7-vue')['f7App']
    F7Block: typeof import('framework7-vue')['f7Block']
    F7Button: typeof import('framework7-vue')['f7Button']
    F7Icon: typeof import('framework7-vue')['f7Icon']
    F7Link: typeof import('framework7-vue')['f7Link']
    F7List: typeof import('framework7-vue')['f7List']
    F7ListInput: typeof import('framework7-vue')['f7ListInput']
    F7ListItem: typeof import('framework7-vue')['f7ListItem']
    F7Navbar: typeof import('framework7-vue')['f7Navbar']
    F7NavRight: typeof import('framework7-vue')['f7NavRight']
    F7Page: typeof import('framework7-vue')['f7Page']
    F7PageContent: typeof import('framework7-vue')['f7PageContent']
    F7Segmented: typeof import('framework7-vue')['f7Segmented']
    F7Sheet: typeof import('framework7-vue')['f7Sheet']
    F7Toggle: typeof import('framework7-vue')['f7Toggle']
    F7Toolbar: typeof import('framework7-vue')['f7Toolbar']
    F7View: typeof import('framework7-vue')['f7View']
    F7Views: typeof import('framework7-vue')['f7Views']
    InstallControl: typeof import('./src/modules/apps/components/InstallControl.vue')['default']
    LaneRail: typeof import('./src/modules/apps/components/LaneRail.vue')['default']
    LiveIndicator: typeof import('./src/shared/components/app/LiveIndicator.vue')['default']
    LoadingIndicator: typeof import('./src/shared/components/progress/LoadingIndicator.vue')['default']
    MaterialShape: typeof import('./src/shared/components/shape/MaterialShape.vue')['default']
    PhoneBadge: typeof import('./src/modules/apps/components/PhoneBadge.vue')['default']
    PhoneCard: typeof import('./src/modules/apps/components/PhoneCard.vue')['default']
    ProfileView: typeof import('./src/modules/profile/views/ProfileView.vue')['default']
    SearchBar: typeof import('./src/modules/apps/components/SearchBar.vue')['default']
    SignInHero: typeof import('./src/modules/auth/components/SignInHero.vue')['default']
    SignInView: typeof import('./src/modules/auth/views/SignInView.vue')['default']
    WavyProgress: typeof import('./src/shared/components/progress/WavyProgress.vue')['default']
  }
}
