import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it, vi } from "vite-plus/test";
import CiInit from "./init.js";

const CLI_ROOT = fileURLToPath(new URL("../../..", import.meta.url));
const CLI_VERSION = (
  JSON.parse(fs.readFileSync(path.join(CLI_ROOT, "package.json"), "utf8")) as { version: string }
).version;

describe("capuchoo ci init", () => {
  let dir: string;
  let app: string;
  let previous: string;
  let stdout: string;
  let stderr: string;

  beforeEach(() => {
    previous = process.cwd();
    dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "capuchoo-ci-init-")));
    app = path.join(dir, "apps", "shop");
    fs.mkdirSync(app, { recursive: true });
    fs.mkdirSync(path.join(dir, ".git"));
    process.chdir(app);
    stdout = "";
    stderr = "";
    vi.spyOn(process.stdout, "write").mockImplementation(() => true);
    vi.spyOn(console, "log").mockImplementation((...args: unknown[]) => {
      stdout += `${args.join(" ")}\n`;
    });
    vi.spyOn(process.stderr, "write").mockImplementation((chunk) => {
      stderr += String(chunk);
      return true;
    });
    vi.spyOn(process, "exit").mockImplementation((code) => {
      throw new Error(`exit ${code}`);
    });
  });

  afterEach(() => {
    vi.restoreAllMocks();
    process.chdir(previous);
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const workflow = () => path.join(dir, ".github", "workflows", "capuchoo.yml");

  it("writes the GitHub workflow at the repository root, then reports it unchanged", async () => {
    await CiInit.run(
      ["--github", "--default-branch", "main", "--clients", "acme", "--json"],
      CLI_ROOT,
    );
    const first = JSON.parse(stdout);
    expect(first).toMatchObject({
      ok: true,
      provider: "github",
      state: "created",
      appDir: "apps/shop",
      defaultBranch: "main",
      variable: "CAPUCHOO_ENDPOINT",
    });
    expect(first.file.replaceAll("\\", "/")).toBe("../../.github/workflows/capuchoo.yml");
    const written = fs.readFileSync(workflow(), "utf8");
    expect(written).toContain(`# Generated by Capuchoo ${CLI_VERSION}`);
    expect(written).toContain('APP_DIR: "apps/shop"');

    stdout = "";
    await CiInit.run(
      ["--github", "--default-branch", "main", "--clients", "acme", "--json"],
      CLI_ROOT,
    );
    expect(JSON.parse(stdout).state).toBe("unchanged");
  });

  it("refuses to replace a different file without --yes when nobody can be asked", async () => {
    fs.mkdirSync(path.dirname(workflow()), { recursive: true });
    fs.writeFileSync(workflow(), "name: mine\n");
    await expect(CiInit.run(["--github", "--default-branch", "main"], CLI_ROOT)).rejects.toThrow(
      "exit",
    );
    expect(stderr).toContain("Pass --yes to replace it");
    expect(fs.readFileSync(workflow(), "utf8")).toBe("name: mine\n");

    await CiInit.run(["--github", "--default-branch", "main", "--yes", "--json"], CLI_ROOT);
    expect(fs.readFileSync(workflow(), "utf8")).toContain("name: Capuchoo");
  });

  it("still writes the GitLab pipeline here", async () => {
    await CiInit.run(["--gitlab", "--dev-branch", "develop", "--json"], CLI_ROOT);
    expect(JSON.parse(stdout)).toMatchObject({ provider: "gitlab", state: "created" });
    expect(fs.readFileSync(path.join(app, ".gitlab-ci.yml"), "utf8")).toContain(
      'CAPUCHOO_DEV_BRANCH: "develop"',
    );
  });

  it.each([
    [[], "exactly one of --github or --gitlab"],
    [["--github", "--gitlab"], "exactly one of --github or --gitlab"],
    [["--gitlab", "--app-dir", "apps/shop"], "apply to --github only"],
    [["--github", "--default-branch", "dev"], "three different branches"],
  ])("refuses %j cleanly", async (argv, message) => {
    await expect(CiInit.run(argv, CLI_ROOT)).rejects.toThrow("exit 1");
    expect(stderr).toContain(message);
    expect(stderr).not.toContain("    at ");
    expect(fs.existsSync(workflow())).toBe(false);
    expect(fs.existsSync(path.join(app, ".gitlab-ci.yml"))).toBe(false);
  });
});
